### PR TITLE
Add notice on mainenance bandwidth to readme

### PR DESCRIPTION
**Pull request by alamb**
Closes https://github.com/jorgecarleitao/arrow2/issues/1429

This PR clarifies for current and potential future users that the current maintenance bandwidth for this crate is very limited.  Related to @tustvold 's proposal on https://github.com/jorgecarleitao/arrow2/pull/1464

I also hope it might encourage other current users of arrow2 to offer to help maintain the crate if that is valuable to them.

### CODE REVIEW

**Comment by ritchie46** [comment]
Hey Andrew. Thanks for the PR. I think I can find myself more in this. I am / Polars is willing to maintain arrow2 as it is a huge dependency for us. If we can work out a way to get the API working on arrow-rs, I might consider a switch, but the capacity is not here at the moment.

I think you can mention that development here is slower paced than on arrow-rs. I am definitely willing to fix bugs as I encounter them though. I think that only the development of new features is rather stalled.

**Comment by ritchie46** [comment]
> Given I don't really know what your plans are maybe we should just close this PR as not helpful.

Yes, I don't think it per se helps much. :) I will close this and reconsider it once/if we are further in the transition process. Let's wait out a bit.

**Comment by ritchie46** [comment]
Yeap, it's on my stack. :)

**Comment by mnpw** [comment]
@ritchie46 I noticed the addition of `nano-arrow` crate to `polars` (https://github.com/pola-rs/polars/pull/11179). Does this mean that `arrow2` will receive low maintenance bandwidth going forward? If so then perhaps we can re-open this PR and update the readme.

**Comment by alamb** [comment]
In case anyone else finds this issue:

I believe that pola-rs is  vendoring (aka brought a snapshot of the arrow2 code into their codebase):
* arrow2 https://github.com/pola-rs/polars/pull/11179
* parquet2 https://github.com/pola-rs/polars/pull/12026

**Comment by ritchie46** [comment]
Yes, @alamb is correct, we started vendoring in polars and repelling anything we don't use. See our notice here: https://github.com/pola-rs/polars/pull/11179

**Comment by alamb** [comment]
Related discussion: https://github.com/jorgecarleitao/arrow2/issues/1429

**Pull request closed without merging**
