### PR TITLE
Fixup for new and renamed core::simd fn

### PR DESCRIPTION
**Pull request by workingjubilee**
Pardon our dust!

### CODE REVIEW

**Comment by workingjubilee** [comment]
Oh, the nightly version is pinned, I see.

**Comment by workingjubilee** [comment]
Ah, so the pin will have to be to the next nightly which hasn't been cut yet, because Miri failed a test and the rebuild will happen then.

**Comment by jorgecarleitao** [comment]
thanks a lot @workingjubilee for this PR! Indeed, we pin nightly due to MIRI, since not all nightlies support it.

We could use two nightlies, one for MIRI and one for the `simd`, so that we prove that we can compile under the most recent `std::simd`.

**Comment by workingjubilee** [comment]
Reasonable but simpler to just move forward an additional nightly here. Miri actually supports an increasing number of portable SIMD stuff, so eventually it will be an option to run Miri over the entire codebase, SIMD optimizations included. Also I seem to have mixed up how nightlies are versioned/dated, so it has to tick forward again.

**Comment by ritchie46** [comment]
> Reasonable but simpler to just move forward an additional nightly here. Miri actually supports an increasing number of portable SIMD stuff, so eventually it will be an option to run Miri over the entire codebase, SIMD optimizations included. Also I seem to have mixed up how nightlies are versioned/dated, so it has to tick forward again.

I am for this. I think it is better to always support latest nightly. Currently it is a very specific version which we have to communicate. Whilst saying this I assume the api will stabilize of course. :)

**Comment by workingjubilee** [comment]
Yeah, we're just in an awkward position where we're getting major actual testing/usage and thus picking up things we missed along the way (which lead to this change) and also staring down a difficult design "fork".

**Comment by workingjubilee** [comment]
If I have my numbers right, this should now use a version of the Rust toolchain that runs all the tests, both SIMD and Miri.

**Comment by jorgecarleitao** [comment]
Thank you again @workingjubilee for this PR!

Out of curiosity, how did you know that this would affect arrow2, or is there a mechanism to see which crates are using `std::simd`? Curious because I would be interested in knowing this mechanism ^^

**Comment by workingjubilee** [comment]
Magic powers! (I guessed)

**Pull request merged**
