### PR TITLE
use edition 2021

### PR DESCRIPTION
**Pull request by Jimexist**

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
Thanks @Jimexist! Could you check https://github.com/jorgecarleitao/arrow2/pull/571 ? 

The context is that [I was recommended](https://www.reddit.com/r/rust/comments/qmph74/should_i_bump_to_2021_edition/) to wait.

**Comment by Jimexist** [comment]
> Thanks @Jimexist! Could you check #571 ?
> 
> The context is that [I was recommended](https://www.reddit.com/r/rust/comments/qmph74/should_i_bump_to_2021_edition/) to wait.

Thanks for the context.

2 months have passed and i believe 2021 edition should be widely adopted either way. But YMMV, there's no harm parking this one here.

**Comment by jorgecarleitao** [comment]
Cc @sundy-li , @ritchie46 , @sd2k - have you migrated? Would this be an issue?

**Comment by sundy-li** [comment]
Yes，databend is using edition 2021 now.

**Comment by ritchie46** [comment]
Polars is also on edition 2021.

**Comment by sd2k** [comment]
Yep, same for the Grafana plugin SDK.

**Comment by jorgecarleitao** [comment]
Thanks everyone for your input, and @Jimexist for the PR! Set sail, then!

**Pull request merged**
