### PR TITLE
add ordering

### PR DESCRIPTION
**Pull request by Igosuki**
Hi guys, I'm currently trying out arrow2 with the latest master from datafusion.  The following updates were necessary because TypeSignature is ordered.

P.S. : The other commits are just me removing code only needed to add Decimal support.

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
Thanks for this PR. Could you check https://github.com/jorgecarleitao/arrow2/pull/379?

**Comment by Igosuki** [comment]
Ok, so the requirement for PartialOrd is lifted so we can close this !

**Comment by jorgecarleitao** [comment]
Thanks @Igosuki , and also for all your work in the datafusion migration 🙇

**Comment by Igosuki** [comment]
👍

**Pull request closed without merging**
