### PR TITLE
Added support to write nested parquet

### LINKED ISSUE #830: Writing to Parquet fails for extension types that contain lists
If you create an extension type that wraps any kind of list type,  conversion to Parquet format fails. 
As far as I can tell, this could be fixed by updating  the `nested_array_to_page` function in `io/parquet/write/mod.rs` to use:
```rust
match array.data_type().to_logical_type() {
```
instead of 
```rust
match array.data_type() {
```

### LINKED ISSUE #992: Write a two-dimensional list to parquet file failed
Write a two-dimensional list to parquet file failed

sample code:
```rust
use std::fs::File;
use std::sync::Arc;

use arrow2::{
    array::{Array, ListArray, PrimitiveArray},
    chunk::Chunk,
    datatypes::{DataType, Field, Schema},
    error::Result,
    io::parquet::write::{
        CompressionOptions, Encoding, FileWriter, RowGroupIterator, Version, WriteOptions,
    },
};

type LargeListArray = ListArray<i64>;

fn write_batch(path: &str, schema: Schema, columns: Chunk<Arc<dyn Array>>) -> Result<()> {
    let options = WriteOptions {
        write_statistics: true,
        compression: CompressionOptions::Uncompressed,
        version: Version::V2,
    };

    let iter = vec![Ok(columns)];

    let row_groups =
        RowGroupIterator::try_new(iter.into_iter(), &schema, options, vec![Encoding::Plain])?;

    // Create a new empty file
    let file = File::create(path)?;

    let mut writer = FileWriter::try_new(file, schema, options)?;

    writer.start()?;
    for group in row_groups {
        let g = group?;
        writer.write(g)?;
    }
    let _size = writer.end(None)?;
    Ok(())
}

fn main() -> Result<()> {
    let data_field = Field::new(
        "test",
        DataType::LargeList(Box::new(Field::new(
            "list",
            DataType::LargeList(Box::new(Field::new("list", DataType::Int64, false))),
            false,
        ))),
        false,
    );
    let schema = Schema::from(vec![data_field]);

    let mut values: Vec<i64> = Vec::with_capacity(9);

    let mut list_last_size1: usize = 0;
    let mut list_offsets1: Vec<i64> = Vec::with_capacity(3);
    list_offsets1.push(0);

    let mut list_offsets2: Vec<i64> = Vec::with_capacity(3);
    list_offsets2.push(0);

    let vals = vec![vec![1, 2, 3], vec![4, 5, 6], vec![7, 8, 9]];
    list_offsets2.push(vals.len() as i64);
    for val in vals {
        list_last_size1 += val.len();
        list_offsets1.push(list_last_size1 as i64);
        for v in val {
            values.push(v);
        }
    }

    let i64_array = Arc::new(PrimitiveArray::<i64>::from_data(
        DataType::Int64,
        values.into(),
        None,
    ));

    let data_type1 = DataType::LargeList(Box::new(Field::new(
        "list".to_string(),
        DataType::Int64,
        false,
    )));
    let list_array1 = Arc::new(LargeListArray::from_data(
        data_type1,
        list_offsets1.into(),
        i64_array,
        None,
    ));

    let data_type2 = DataType::LargeList(Box::new(Field::new(
        "list",
        DataType::LargeList(Box::new(Field::new("list", DataType::Int64, false))),
        false,
    )));

    let list_array2 = Arc::new(LargeListArray::from_data(
        data_type2,
        list_offsets2.into(),
        list_array1,
        None,
    ));

    let columns = Chunk::new(vec![list_array2 as Arc<dyn Array>]);

    let file_path = "test.parquet";
    match write_batch(file_path, schema, columns) {
        Ok(_) => println!("write ok"),
        Err(e) => println!("write err: {:#?}", e),
    }

    Ok(())
}
```
output
```
write err: ExternalFormat(
    "Invalid argument error: The GroupType {
        field_info: FieldInfo {
            name: \"list\",
            repetition: Required,
            id: None
        },
        logical_type: Some(List),
        converted_type: None,
        fields: [
            GroupType {
                field_info: FieldInfo {
                    name: \"list\",
                    repetition: Repeated,
                    id: None
                },
                logical_type: None,
                converted_type: None,
                fields: [
                    PrimitiveType(PrimitiveType {
                        field_info: FieldInfo {
                            name: \"list\",
                            repetition: Required,
                            id: None
                        },
                        logical_type: None,
                        converted_type: None,
                        physical_type: Int64
                    })
                ]
            }
        ]
    } is not a primitive type but it is trying to describe a primitive array",
)
```

### LINKED ISSUE #1008: Writing of `ListArray` does not preserve all values
Not sure if this is related to the on-going work on supporting nested data (https://github.com/jorgecarleitao/arrow2/pull/1007). Noticed that when creating Parquet files that contain a `ListArray` type, the list is missing some data. 

Example Parquet generation:
```
import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq

d = {
    "id": pd.Series(['t1', 't2', 't3']),
    "prices": pd.Series([
        [10.0, 20.0, 30.0, 40.0],
        [100.0, 200.0, 300.0, 400.0],
        [1000.0, 2000.0, 3000.0, 4000.0],
    ])
}

df = pd.DataFrame(d2)
table = pa.Table.from_pandas(df)
pq.write_table(table, '/tmp/demo_one_arrow.parquet')
```

Code to read the Parquet generated above and write out as another Parquet:
```
use arrow2::{
    array::*,
    chunk::Chunk as AChunk,
    io::parquet::write::{FileWriter, RowGroupIterator, WriteOptions},
};
use arrow2::{datatypes::Schema, io::parquet::read::FileReader};
use parquet2::encoding::Encoding;
use std::{fs::File, sync::Arc};

type Chunk = AChunk<Arc<dyn Array>>;
type Result<T> = arrow2::error::Result<T>;

pub fn main() -> Result<()> {
    let filename = "/tmp/demo_one_arrow.parquet";
    // Read the Parquet created by PyArrow
    let (schema, chunks) = read_parquet(filename);
    println!("Expected chunks: {:#?}", chunks);
    
    let arrow2_parquet_filename = "/tmp/demo_one_arrow2.parquet";
    // Write a new Parquet file from what what we just read
    write_parquet(arrow2_parquet_filename, schema, chunks)?;

    // Read what we just wrote
    let (_schema, _chunks) = read_parquet(arrow2_parquet_filename);
    println!("Chunks written: {:#?}", _chunks);

    Ok(())
}

fn read_parquet(filename: &str) -> (Schema, Vec<Result<Chunk>>) {
    let reader = File::open(filename).unwrap();
    let reader = FileReader::try_new(reader, None, None, None, None).unwrap();
    let schema: Schema = reader.schema().clone();
    // println!("schema: {:#?}", schema);
    let mut chunks = vec![];
    for chunk_result in reader {
        chunks.push(chunk_result);
    }
    (schema, chunks)
}

fn write_parquet(path: &str, schema: Schema, chunks: Vec<Result<Chunk>>) -> Result<()> {
    let options = WriteOptions {
        write_statistics: true,
        version: parquet2::write::Version::V2,
        compression: parquet2::compression::CompressionOptions::Snappy,
    };

    let iter = chunks.into_iter();
    let encodings = schema.fields.iter().map(|_| Encoding::Plain).collect();
    let row_groups = RowGroupIterator::try_new(iter, &schema, options, encodings)?;

    let file = std::fs::File::create(path)?;
    let mut writer = FileWriter::try_new(file, schema, options)?;
    writer.start()?;
    for group in row_groups {
        writer.write(group?)?;
    }
    writer.end(None)?;
    Ok(())
}
```

Output:
```
Expected chunks: [
    Ok(
        Chunk {
            arrays: [
                Utf8Array[t1, t2, t3],
                ListArray[[10, 20, 30, 40], [100, 200, 300, 400], [1000, 2000, 3000, 4000]],
            ],
        },
    ),
]
Chunks written: [
    Ok(
        Chunk {
            arrays: [
                Utf8Array[t1, t2, t3],
                ListArray[[10, 20, 30, 40], [100, 200], None],
            ],
        },
    ),
]
```

Hence, as we see, when we write the new Parquet file, it's not writing the `ListArray` properly.   Perhaps this is already being addressed in https://github.com/jorgecarleitao/arrow2/pull/1007.

### LINKED ISSUE #1012: Require one encoding per parquet column on write
When writing to parquet, we should require `Vec<Vec<Encoding>>`, not `Vec<Encoding>`, since an array may contain multiple parquet columns.

### PR DESCRIPTION
**Pull request by jorgecarleitao**
This PR adds support to write `StructArray` (and likely arbitrary nested, but more testing is required).

* Closes #1012
* Closes #1008
* Closes #992
* Closes #830

I expect the operation to be (per array) `O(N * D * C)` (worse case) where:
* `D` is the max depth
* `N` the number of items.
* `C` is the number of leaf parquet columns

The main idea in this PR: given a (potentially nested) parquet field (`ParquetType`) and an `Array`, 

1. create a `Vec<Nested>` containing the validities and lengths of each nest level.
2. map `Vec<Nested>` to iterators of rep and def levels.
3. encode the iterators

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
This is now ready - more tests, generalized to arbitrary nesting, and tests demo that we can write `StructArray`.

**Comment by ritchie46** [comment]
Awesome work @jorgecarleitao!

**Comment by ahmedriza** [comment]
Many thanks for the quick fix.  Fantastic work.

**Comment by ahmedriza** [comment]
Tested a two level nested Parquet against this branch.  Unfortunately, the Parquet reading fails.  Submitted a separate issue: https://github.com/jorgecarleitao/arrow2/issues/1014.

**Pull request merged**
