### PR TITLE
Added `BinaryArray::into_mut` and double-ended support for its iterator

### PR DESCRIPTION
**Pull request by ozgrakkurt**
Copy pasted the implementation of `Utf8ValuesIter`

### CODE REVIEW

**Comment by ozgrakkurt** [comment]
Hey @jorgecarleitao, I think the tests are failing because of the code that already exists in main branch

**Comment by jorgecarleitao** [comment]
Thanks for the PR!!

I will fix clippy. Meanwhile, it would be important to have some tests on this. Could you add them or would you like me to?

**Comment by ozgrakkurt** [comment]
@jorgecarleitao added some tests

**Comment by ozgrakkurt** [comment]
also closes #1263

**Comment by jorgecarleitao** [comment]
Thanks a lot @ozgrakkurt , this is really good stuff. We just released 0.14.1 (https://github.com/jorgecarleitao/arrow2/releases/tag/v0.14.1) with this, in case you depend on this being available.

**Comment by ozgrakkurt** [comment]
@jorgecarleitao thanks!

**Pull request merged**
