### PR TITLE
Made GroupFilter optional in  parquet's`RecordReader` and added method to set it.

### PR DESCRIPTION
**Pull request by jorgecarleitao**
This is more expressive since filtering is optional.

# Backward incompatible changes

The function `RecordReader::try_new` now expects `Option<GroupFilter>` instead of `GroupFilter`. If you were not using filtering, migrate to this by passing `None`. If you were filtering, pass `Some(...)` instead.

### CODE REVIEW

**Review by houqp — APPROVED** [review]
Could we also expose `RecordReader.metadata` so it can be used to build the row group filter?

**Comment by jorgecarleitao** [comment]
> Could we also expose `RecordReader.metadata` so it can be used to build the row group filter?

done 👍

**Review by houqp — APPROVED** [review]
LGTM

**Comment by jorgecarleitao** [comment]
This has been released under [`v0.5.0`](https://github.com/jorgecarleitao/arrow2/releases/tag/v0.5.0), @houqp

**Comment by houqp** [comment]
I am using git commit in my local arrow2 migration branch at the moment, but good to know we could release at a much faster cadence :D

**Pull request merged**
