### PR TITLE
Return error when reading Parquet column with invalid utf-8 bytes

### PR DESCRIPTION
**Pull request by danburkert**
This PR switches the Parquet reading internals to return an error
instead of panicking when data with invalid utf-8 bytes is read. Per the
advice in #804 I did this by introducing new `try_*` variants of methods
which panic, and switched the callstack over. Thus, I believe this is an
API compatible change (`TraitBinaryArray` is changed incompatibly, but
it appears to be crate private).

I've attached a very small .parquet file with an invalid utf-8 byte that
I used for testing. Without this change using the
`parquet_read_parallel` example binary with the file panics, whereas now
it errors. I think this file should be added to the test suite, but I
need some guidance as to exactly how to structure that.

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
looks great!

What do you think about renaming `try_from_data` to `try_new`? I believe that this is more idiomatic in Rust (imo `from_data` should also be changed to `new` at some point).

**Comment by jorgecarleitao** [comment]
would it be possible to write the parquet file as a `vec![]` in the tests themselves? This allows the test to run against MIRI without disabling isolation (MIRI does not accept opening a file).

I think it would also be worthwhile to have a test against the file so that we show that invalid utf8 error.

**Comment by danburkert** [comment]
> What do you think about renaming try_from_data to try_new? I believe that this is more idiomatic in Rust (imo from_data should also be changed to new at some point).

Sounds good.

> would it be possible to write the parquet file as a Vec<u8> in the tests themselves? This allows the test to run against MIRI without disabling isolation (MIRI does not accept opening a file).

I can definitely do that - is there a test suite file that you have in mind?

**Comment by jorgecarleitao** [comment]
> I can definitely do that - is there a test suite file that you have in mind?

Somewhere here: https://github.com/jorgecarleitao/arrow2/blob/main/tests/it/io/parquet/read.rs ?

**Comment by danburkert** [comment]
Methods are renamed, and test is added.

**Comment by jorgecarleitao** [comment]
Thanks a lot, @danburkert.

**Pull request merged**
