### PR TITLE
Upgrade to ahash v0.8

### PR DESCRIPTION
**Pull request by benesch**
Hey @jorgecarleitao! Just looking to avoid a duplicate dependency downstream, and this looked to drop in easily.

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
This broke main and I missed it somehow when approving :/

**Comment by jorgecarleitao** [comment]
I just reverted this until we can fix it - see #1274

**Comment by benesch** [comment]
Thanks for being so on top of it! #1274 seems to have passed tests, unlike this PR! Anything you need me to do?

**Comment by jorgecarleitao** [comment]
We need to fix the #1274 - it is failing to compile on wasm32

**Comment by benesch** [comment]
> We need to fix the #1274 - it is failing to compile on wasm32

Ah, thanks! I believe I've fixed it in #1297.

**Pull request merged**
