### PR TITLE
Dense tensor definition

### PR DESCRIPTION
**Pull request by elferherrera**
Initial definition of dense tensor. It includes constructor and functions to interact with it

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
Hi @elferherrera , thanks a lot for this! 

I looked it up for integration files to perform integration tests, but I have not found any. I can see that the arrow crate itself also has no integration tests for tensors, which suggests that this feature is not well maintained.

A concern I have is that we would offer tensor support, but then have no process of verifying its compatibility against other implementations, which IMO is the hallmark of the arrow format. It is true that the arrow crate itself has no support, but without integration tests, there is no proof that what it is done there is in spec, right?

Do you have an idea on how we should handle this?

**Comment by elferherrera** [comment]
Hi. Actually that is something I want to write about in the mailing list. I know they have dense and sparse tensor definitions in C++ implementation but I couldn't find how they are testing it. I have an idea of how to add it to the new IPC format you have but I was wondering how we can test it with the C++ side.

I guess it will have to be a joint effort with the C++ team, unless they are not interested in this feature.

**Comment by elferherrera** [comment]
What do you think we should do with these tensors?. I would like to write more implementations for dense and sparse tensors, especially to be able to use them with IPC. However, I dont think they will be consider them soon into main Arrow.

**Comment by jorgecarleitao** [comment]
Firstly, thanks a lot for driving that in the mailing list..

I think that we should not have added them to the master arrow crate in the first place, as there is no guarantee that they can be used throughout the ecosystem. IMO we should not invest time on them without IPC tests, as we risk drifting from the specification, which IMO is detrimental to the arrow project as a whole.

I think that the path forward in this direction is to write a google docs describing the json-integration for tensors and share them on the mailing list, so that folks from C++ and the spec itself can take a look and see whether the format would make sense. Note that these are very simple files in json. E.g. the validity is just "true" / "false".

**Pull request closed without merging**
