### PR TITLE
Add comparison for boolean array

### PR DESCRIPTION
**Pull request by jorgecarleitao**

### CODE REVIEW

**Review by elferherrera — COMMENTED** [review]
Would it be a good idea to add a `any` function that returns true is at least one value is true. Or `all` if all are true?

**Comment by jorgecarleitao** [comment]
> Would it be a good idea to add a `any` function that returns true is at least one value is true. Or `all` if all are true?

I agree. I do think that that is an aggregation (aka horizontal) operation, right? It is something like (`f(BooleanArray) -> Option<bool>`)?

**Comment by elferherrera** [comment]
> I agree. I do think that that is an aggregation (aka horizontal) operation, right? It is something like (f(BooleanArray) -> Option<bool>)?

That's precisely what Im thinking. Im just not sure it needs to be an Option<bool>. In what case would it be None?

**Comment by jorgecarleitao** [comment]
Yeap, it does not need option. ^_^

**Pull request merged**
