### PR TITLE
add a test case of incorrect merge sort

### PR DESCRIPTION
**Pull request by sundy-li**
Related 

https://github.com/jorgecarleitao/arrow2/commit/fa3b003759d5a98200a98ed93facb8751f3aa6a0

Found in https://github.com/datafuselabs/datafuse/pull/1575

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
found the root cause, fixing it

**Comment by jorgecarleitao** [comment]
This is fixed by #327

**Comment by jorgecarleitao** [comment]
Thanks a lot for taking the time to write a minimal test case; very useful! (also glad that you are using the merge-sort compute kernel; was not sure if it would ever be used ^_^)

**Comment by sundy-li** [comment]
> Thanks a lot for taking the time to write a minimal test case; very useful! (also glad that you are using the merge-sort compute kernel; was not sure if it would ever be used ^_^)

Thanks for the fix.  The merge-sort kernel is useful, and it also can be optimized by heap-sort when the limit option is very small (holding a priority queue in memory to reduce the compare times). I've created an issue in #329 to track it.

**Pull request closed without merging**
