### PR TITLE
Replaced `MutableBuffer` by `std::Vec`

### PR DESCRIPTION
**Pull request by jorgecarleitao**
This PR replaces

* `cache_aligned` cargo feature
* the custom implementation of `Vec` under the feature gate
* the custom allocator
* `MutableBuffer`

by Rust's `std::vec::Vec`.

We still need `Bytes` for the ffi, but this significantly simplifies the APIs for Rust users.

# Backward incompatible changes

To migrate:

1. replace `Buffer::from(slice)` by `Buffer::from_slice(slice)` (`from` is now from `Vec`)
2. replace `.from_trusted_len_iter` and the like by `.extend` (since the std lib supports specialization and will pick the trusted len implementation by default)
3. replace `MutableBuffer` by `Vec`
4. replace `a.extend_constant(additional, value)` by `a.resize(a.len() + additional, value)`

### CODE REVIEW

**Comment by ritchie46** [comment]
This is awesome! <3

**Comment by jorgecarleitao** [comment]
@sundy-li , would this be ok for you?

**Comment by sundy-li** [comment]
That's ok since they have similar pub methods.

**Comment by jorgecarleitao** [comment]
`MutableBuffer` was needed due to the custom allocator aligned to cache lines, under the feature flag `cache_aligned`. This PR proposes removing the custom allocator (and consequently the `MutableBuffer`). I never saw any difference between them, and using `Vec` is safer and much lower maintenance (imo).

**Pull request merged**
