### PR TITLE
Made bitmap not cache null count

### PR DESCRIPTION
**Pull request by jorgecarleitao**
This PR removes the cached `null_count` on `Bitmap`, making the computation only happen on request.

This makes the struct simpler and removes the need to compute the count even if the count will not be used.

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
what do you think @ritchie46 @houqp @Dandandan ?

**Comment by ritchie46** [comment]
What do you think about a lazy cache? Same to `init_validities()`. That we only set the null count at first request. I can imagine that we have long living arrays that are base for many computations. 

For instance in Polars, almost every operation starts with a null_count check to see if we can use a fast path.

**Comment by jorgecarleitao** [comment]
Doesn't lazy initialization require `&mut self`?

> For instance in Polars, almost every operation starts with a null_count check to see if we can use a fast path.

shouldn't it start with `if let Some(bitmap) = array.validity()`? Or is it common to have arrays with only null values?

**Comment by ritchie46** [comment]
> Doesn't lazy initialization require `&mut self`?
> 
> > For instance in Polars, almost every operation starts with a null_count check to see if we can use a fast path.
> 
> shouldn't it start with `if let Some(bitmap) = array.validity()`? Or is it common to have arrays with only null values?

The series has potentially multiple chunks, so we check null_count. But indeed, I could add the branch check for the validity and return 0 if it is missing. Thanks, now it should not matter that much.

**Comment by ritchie46** [comment]
Just for clarity, I think it is a good enhancement. :+1:  :)

**Comment by jorgecarleitao** [comment]
Reverted because it triggered a major regression in polars, so more care is needed here.

**Pull request merged**
