### PR TITLE
Transform like pattern to regex

### PR DESCRIPTION
**Pull request by zhyass**
Add transform like pattern to regex to fixes https://github.com/datafuselabs/databend/issues/2478 .

1. Use backslash to escape the regex special character.
2. Process the backslash escape.

e.g. 
'Hello\\._World%\\%' tranform to '^Hello\\\\\\..World.*%$'.

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
Hi, I do not think we should do this in `regex` function: there are too many edge cases in the different flavors of regex, making it impossible to please everyone. 

I have two suggestions:

1. make DataBlend implement its own regex, based on the specific rules that you would like (mysql?).
2. Alternatively, define a new regex here called `regex_mysql`, that implements the semantics mysql's regex

**Comment by zhyass** [comment]
> Hi, I do not think we should do this in `regex` function: there are too many edge cases in the different flavors of regex, making it impossible to please everyone.
> 
> I have two suggestions:
> 
>     1. make DataBlend implement its own regex, based on the specific rules that you would like (mysql?).
> 
>     2. Alternatively, define a new regex here called `regex_mysql`, that implements the semantics mysql's regex

Thanks! I will try to realize the first suggestion. The pr will be closed.

**Comment by jorgecarleitao** [comment]
feel free to ping me there if you would like me to take a look at it 👍

**Comment by sundy-li** [comment]
> make DataBlend implement its own regex, based on the specific rules that you would like (mysql?).

Hello, there is a typo, its name is Databend

**Pull request closed without merging**
