### PR TITLE
Generalized "take" for unsigned.

### PR DESCRIPTION
**Pull request by jorgecarleitao**

### CODE REVIEW

**Comment by jorgecarleitao** [comment]
cc @ritchie46

**Review by elferherrera — COMMENTED** [review]
I'm lost on this one. What advantages does it have over the previous take?

**Comment by jorgecarleitao** [comment]
Sorry, @elferherrera , was not very clear: it allows taking indexes as `u32`, `i32`, `i64` and `u64`, like the arrow crate does.

**Comment by elferherrera** [comment]
@jorgecarleitao I see. That makes it more versatile. Nicely done.

**Pull request merged**
